#!/usr/bin/env ruby

require_relative 'lib/environment'
Environment.environment = ENV["DB"] || "development"

require_relative 'lib/router'

def clean_gets
  (gets || "").chomp
end

puts IO.readlines('beer.txt')

regions_controller = RegionsController.new()
regions_controller.list
