#!/usr/bin/env ruby

require_relative 'lib/environment'
Environment.environment = ENV["DB"] || "test"

require_relative 'lib/router'

def clean_gets
  (gets || "").chomp
end

puts 'Welcome! Grab a seat and take a load off. Drink and be happy and we will do the rest'
puts IO.readlines('beer.txt')

puts 'Select the region you would like to explore and taste their beer'

regions_controller = RegionsController.new()
regions_controller.list
